src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using DevAdventCalendarCompetition.Models.Test;
using DevAdventCalendarCompetition.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace DevAdventCalendarCompetition.Controllers
{
    [Route("[controller]/[action]")]
    public class ResultsController : Controller
    {
        private readonly IResultsService _resultsService;

        public ResultsController(IResultsService resultsService)
        {
            this._resultsService = resultsService ?? throw new ArgumentNullException(nameof(resultsService));
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userId = this.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return this.View();
            }

            var userPosition = this._resultsService.GetUserPosition(userId);
            var vm = new TestResultsViewModel()
            {
                UserWeek1Position = userPosition.Week1Place ?? 0,
                UserWeek2Position = userPosition.Week2Place ?? 0,
                UserWeek3Position = userPosition.Week3Place ?? 0,
                UserFinalPosition = userPosition.FinalPlace ?? 0
            };

            return this.View(vm);
        }

        [HttpGet]
        public ActionResult RenderResults(int pageIndex = 1, int weekNumber = 1)
        {
            var userId = this.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return this.RedirectToAction("Index");
            }

            const int pageSize = 50;

            var testResultListDto = this._resultsService.GetTestResults(weekNumber, pageSize, pageIndex);
            if (testResultListDto == null || !testResultListDto.Any())
            {
                return this.PartialView("_ResultsPage", new KeyValuePair<int, PaginatedCollection<TestResultEntryViewModel>>(weekNumber, null));
            }

            var totalTestResults = testResultListDto
                    .Select(t => new TestResultEntryViewModel
                    {
                        Points = t.Points,
                        Position = t.Position,
                        UserId = t.UserId,
                        CorrectAnswers = t.CorrectAnswersCount,
                        WrongAnswers = t.WrongAnswersCount,
                        UserName = t.UserName,
                        TotalTime = t.TotalTime
                    })
                    .ToList();

            var totalPages = (int)Math.Ceiling((double)this._resultsService.GetTotalTestResultsCount(weekNumber) / pageSize);

            var paginatedResults = new KeyValuePair<int, PaginatedCollection<TestResultEntryViewModel>>(
                weekNumber, new PaginatedCollection<TestResultEntryViewModel>(totalTestResults, pageIndex, pageSize, totalPages));

            return this.PartialView("_ResultsPage", paginatedResults);
        }
    }
}

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/TestAnswered.cshtml
@using static DevAdventCalendarCompetition.Resources.ViewsMessages

@{
    ViewBag.Title = @GoodAnswer;
}

<div class="breadcrumb_area">
    <div class="container">
        <div class="row">
            <div class="breadcrumb_wrapper">
                <div class="page_title page_title--block text-center">
                    <h3>@Congrats</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="promot_section">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-sm-offset-2 col-md-offset-3">
                <div class="promot_content_wrapper">
                    <div class="promt_content area_title">
                        <h3>@ViewBag.Title</h3>
                    </div>
                    <div class="gift_box">
                        <img src="~/theme-2019/images/santa_with_bag.png" alt="Begger_santa">
                    </div>
                    <div>
                        <br />
                        <a href="/Home/Index" class="chris_btn">@Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_Layout.cshtml
@using static DevAdventCalendarCompetition.Resources.ViewsMessages

<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" lang="pl-PL">
<head>
    <meta charset="UTF-8">

    <!-- viewport meta -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@HeadTitle</title>
    <meta name="description" content="DevAdventCalendar - inicjatywa łącząca tradycję kalendarza adwentowego z programowaniem. Celem jest stworzenie konkursu dla osób związanych ze światem IT. " />
    <meta property="og:image" content="https://www.devadventcalendar.pl/theme-2019/images/dac2019-social.png">
    <meta property="og:title" content="DevAdventCalendar - programistyczny kalendarz adwentowy" />
    <meta property="og:description" content="DevAdventCalendar - inicjatywa łącząca tradycję kalendarza adwentowego z programowaniem. Celem jest stworzenie konkursu dla osób związanych ze światem IT." />
    <meta property="og:url" content="https://devadventcalendar.pl/" />
    <meta property="og:type" content="website" />
    <meta property="fb:app_id" content="1404040546394606" />

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-74536209-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-74536209-2');
    </script>

    <!-- owl carousel css -->
    <link rel="stylesheet" href="~/theme-2019/css/owl.carousel.css" />

    <!-- font icofont -->
    <link rel="stylesheet" href="~/theme-2019/css/icofont.css" />
    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700|Roboto+Slab:100,300,400,700" rel="stylesheet">

    <!-- bootstrap -->
    <link rel="stylesheet" href="~/theme-2019/css/bootstrap.min.css" />

    <!-- bootstrap social -->
    <link rel="stylesheet" href="~/css/bootstrap-social.css" />

    <!-- bootstrap toggle -->
    <link rel="stylesheet" href="~/theme-2019/css/bootstrap4-toggle.min.css" />

    <!-- animate css -->
    <link rel="stylesheet" href="~/theme-2019/css/animate.css" />

    <!-- style css -->
    <link rel="stylesheet" href="~/theme-2019/style.css" />

    <!-- responsive css -->
    <link rel="stylesheet" href="~/theme-2019/css/responsive.css">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="~/theme-2019/images/favicon.png" />
</head>

<body>
    <!-- preloader -->
    <div class="preloader">
        <div class="preloader-container">
            <span class="animated-preloader"></span>
        </div>
    </div>

    <section class="header_area">
        <!-- NAV AREA CSS -->
        <div class="nav_area">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">

                        <!-- MENU AREA STARTS HERE -->
                        <div class="menu_area">
                            <div class="logo_container">
                                <a asp-area="" asp-controller="Home" asp-action="Index">
                                    <img src="~/theme-2019/images/logo.png" alt="logo Image">
                                </a>
                            </div>
                            <div class="main_menu">
                                <!-- nav toggle hamberger -->
                                <a class="menu_toggler" href="#">
                                    <div class="hamberger"></div>
                                </a>

                                <div class="offset_menu">
                                    <div class="menu_wrapper">
                                        <div class="cross">
                                            <span class="left"></span>
                                            <span class="right"></span>
                                        </div>
                                        <ul>
                                            <li><a asp-area="" asp-controller="Home" asp-action="Index">&#9924;</a></li>
                                            <li><a asp-area="" asp-controller="Results" asp-action="Index">@Results</a></li>
                                            <li><a asp-area="" asp-controller="Home" asp-action="Partners">@Partners</a></li>
                                            <li><a asp-area="" asp-controller="Home" asp-action="Prizes">@Prizes</a></li>
                                            <li><a asp-area="" asp-controller="Home" asp-action="About">@About</a></li>
                                            <li><a asp-area="" asp-controller="Home" asp-action="Contact">@Contact</a></li>

                                            <!-- login partial -->
                                            <partial name="_LoginPartial" />
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- MENU AREA ENDS HERE -->
                    </div>
                </div>
            </div>
        </div>
        <!-- NAV AREA -->
    </section>

    <main class="main_container">
        @RenderBody()
    </main>

    <!--================================
          START FOOTER
    =================================-->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-4 br-r">
                    <div class="social_icons">
                        <ul>
                            <li><a rel="noopener noreferrer" href="https://www.facebook.com/devadventcalendar/" target="_blank"><span class="icofont icofont-social-facebook"></span></a></li>
                            <li><a rel="noopener noreferrer" href="https://twitter.com/dev_advent_cal" target="_blank"><span class="icofont icofont-social-twitter"></span></a></li>
                            <li><a rel="noopener noreferrer" href="https://www.youtube.com/channel/UCVyWg3P3hqUfE70btpVobfQ" target="_blank"><span class="icofont icofont-social-youtube-play"></span></a></li>
                            <li><a rel="noopener noreferrer" href="https://github.com/DevAdventCalendar/DevAdventCalendar" target="_blank"><span class="icofont icofont-social-github"></span></a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4 col-sm-4 br-r">
                    <div class="christmas_footer_logo">
                        <img src="~/theme-2019/images/footer_logo.png" alt="Footer logo">
                    </div>
                </div>

                <div class="col-md-4 col-sm-4 ">
                    <div class="legal_text">
                        <p>
                            © @DateTime.Now.Year - DevAdventCalendar<br />
                            <a href="~/polityka.pdf" target="_blank">@PrivacyPolicy</a>
                            <a href="~/regulamin.pdf" target="_blank">@TermsOfUse</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--================================
          END FOOTER
    =================================-->

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <partial name="_CookieConsentPartial" />
    <partial name="_ValidationScriptsPartial" />

    <!--//////////////////// JS GOES HERE ////////////////-->
    <!-- jquery latest version -->
    <script src="~/theme-2019/js/jquery-1.12.3.js"></script>

    <!-- bootstrap js -->
    <script src="~/theme-2019/js/bootstrap.min.js"></script>

    <!-- bootstrap toggle -->
    <script src="~/theme-2019/js/bootstrap4-toggle.min.js"></script>

    <!-- jquery easing 1.3 -->
    <script src="~/theme-2019/js/jquery.easing1.3.js"></script>

    <!-- Owl carousel js-->
    <script src="~/theme-2019/js/owl.carousel.min.js"></script>

    <!-- Snowfall js -->
    <script src="~/theme-2019/js/snowfall.js"></script>

    <!-- jquery count down js -->
    <script src="~/theme-2019/js/jquery.countdown.min.js"></script>

    <!-- waypoint js -->
    <script src="~/theme-2019/js/waypoints.min.js"></script>

    <!-- Main js -->
    <script src="~/theme-2019/js/main.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>